lasytunkki/WSD/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from allaccess.views import OAuthRedirect, OAuthCallback
from Laulutunkki.views import AssociateCallback, AdditionalPermissionsRedirect

from Laulutunkki.models import ForgotPasswordForm, CrispySetPasswordForm, CrispyChangePasswordForm

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'WSD.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),


    # User authentication URLs
    url(r'^accounts/login/$', 'Laulutunkki.views.login', name='login'),
    url(r'^accounts/auth/$', 'Laulutunkki.views.auth_view'),
    url(r'^accounts/logout/$', 'Laulutunkki.views.logout', name='logout'),
    url(r'^accounts/invalid_login/$', 'Laulutunkki.views.invalid_login'),
    url(r'^accounts/register/$', 'Laulutunkki.views.register', name='register'),
    url(r'^accounts/register_success/$', 'Laulutunkki.views.register_success'),


    # OAuth
    url(r'^oauth/accounts/login/(?P<provider>(\w|-)+)/$', AdditionalPermissionsRedirect.as_view(), name='allaccess-login'),
    url(r'^oauth/accounts/callback/(?P<provider>(\w|-)+)/$', AssociateCallback.as_view(), name='allaccess-callback'),


    # Site
    url(r'^$', 'Laulutunkki.views.index', name='index'),

    url(r'^song/(?P<id>\d+)/$', 'Laulutunkki.views.song', name='song'),
    url(r'^song_list/$', 'Laulutunkki.views.song_list', name='song_list'),
    url(r'^create_song/$', 'Laulutunkki.views.create_song', name='create_song'),
    url(r'^edit_song/(?P<id>\d+)/$', 'Laulutunkki.views.edit_song', name='edit_song'),
    url(r'^delete_song/(?P<id>\d+)/$', 'Laulutunkki.views.delete_song', name='delete_song'),
    url(r'^like_song/(?P<id>\d+)/$', 'Laulutunkki.views.like_song', name='like_song'),
    url(r'^dislike_song/(?P<id>\d+)/$', 'Laulutunkki.views.dislike_song', name='dislike_song'),

    url(r'^search/$', 'Laulutunkki.views.search', name='search'),
    url(r'^getSongs/$', 'Laulutunkki.views.getSongs'),

    url(r'^view_profile/$', 'Laulutunkki.views.view_profile', name='view_profile'),
    url(r'^edit_profile/$', 'Laulutunkki.views.edit_profile', name='edit_profile'),

    url(r'^booklet/(?P<id>\d+)/$', 'Laulutunkki.views.booklet', name='booklet'),
    url(r'^booklet_list/$', 'Laulutunkki.views.booklet_list', name='booklet_list'),
    url(r'^create_booklet/$', 'Laulutunkki.views.create_booklet', name='create_booklet'),
    url(r'^edit_booklet/(?P<id>\d+)/$', 'Laulutunkki.views.edit_booklet', name='edit_booklet'),
    url(r'^delete_booklet/(?P<id>\d+)/$', 'Laulutunkki.views.delete_booklet', name='delete_booklet'),
    url(r'^get_booklet/(?P<id>\d+)/$', 'Laulutunkki.views.get_booklet_pdf', name='get_booklet_pdf'),
    url(r'^update_booklet/(?P<id>\d+)/$', 'Laulutunkki.views.update_booklet', name='update_booklet'),




    # Comments : required by fluent-comments
    url(r'^comments/', include('fluent_comments.urls')),


    # Search : required by haystack
    url(r'^search/', include('haystack.urls')),
)

urlpatterns += patterns('',
      #override the default urls
      url(r'^password/change/$',
                    auth_views.password_change,
                    {
                          'template_name' : 'password/password_change.html',
                          'password_change_form' : CrispyChangePasswordForm,
                    },
                    name='password_change'),
      url(r'^password/change/done/$',
                    auth_views.password_change_done,
                    {
                        'template_name' : 'password/password_change_complete.html',
                    },
                    name='password_change_done'),
      url(r'^password/reset/$',
                    auth_views.password_reset,
                    {
                        'template_name': 'password/password_reset.html',
                        'email_template_name': 'password/password_reset_email.html',
                        'password_reset_form': ForgotPasswordForm,
                    },
                    name='password_reset'),
      url(r'^password/reset/done/$',
                    auth_views.password_reset_done,
                    {
                        'template_name': 'password/password_reset_done.html'
                    },
                    name='password_reset_done'),
      url(r'^password/reset/complete/$',
                    auth_views.password_reset_complete,
                    {
                        'template_name': 'password/password_reset_complete.html'
                    },
                    name='password_reset_complete'),
      url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                    auth_views.password_reset_confirm,
          {
              'template_name': 'password/password_reset_confirm.html',
              'set_password_form': CrispySetPasswordForm,
          },
                    name='password_reset_confirm'),

)

from WSD import settings
urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

lasytunkki/Laulutunkki/models.py
# -*- coding: utf8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.forms import ModelForm, Textarea, URLInput

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from datetime import datetime
###### SONG RELATED MODELS #######


# A class for songs
class Song(models.Model):
    title = models.CharField(max_length=120)
    category = models.CharField(max_length=120)
    lyrics = models.TextField()
    extra_verses = models.TextField(blank=True, null=True)

    melody = models.CharField(max_length=120, blank=True, null=True)
    example = models.URLField(blank=True, null=True)
    other_info = models.TextField(blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.title


class SongLike(models.Model):
    user = models.ForeignKey(User, related_name='likes')
    song = models.ForeignKey(Song, related_name='likes')
    created = models.DateTimeField(auto_now_add=True)
    value = models.BooleanField()


class SongForm(ModelForm):
    class Meta:
        model = Song
        fields = ['title', 'category', 'lyrics', 'extra_verses', 'melody', 'example', 'other_info']
        labels = {
            'title' : "Laulun nimi",
            'category' : "Laulun luokka",
            'lyrics' : "Säkeistöt",
            'extra_verses' : "Lisäsäkeistöt",
            'melody' : "Melodia",
            'example' : "Esimerkki laulusta",
            'other_info' : "Lisätietoja",
        }

    def __init__(self, *args, **kwargs):
        super(SongForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class SongAdmin(admin.ModelAdmin):
    search_fields = ["title", "lyrics", "author"]

admin.site.register(Song, SongAdmin)


# A category for songs: e.g. wine songs, water songs, etc.
class Category(models.Model):
    # Should there be a set of choices instead of a free field? E.g. Wine songs, Water songs, etc.
    name = models.CharField(max_length=120)
    description = models.TextField()
    song = models.ForeignKey(Song, related_name='categories')

    def __unicode__(self):
        return self.name


###### BOOKLET RELATED MODELS #######

# A booklet which contains multiple songs in a specific order
class Booklet(models.Model):
    title = models.CharField(max_length=120)
    author = models.ForeignKey(User, related_name='booklet_author')
    pdf_file = models.FileField(upload_to="booklet_pdfs/")
    front_page_image = models.URLField(blank=True, null=True)
    front_page_text = models.CharField(max_length=450, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    previous_version = models.ForeignKey("self", related_name="updated_version", blank=True, null=True)

    def __unicode__(self):
        return self.title


class BookletAdmin(admin.ModelAdmin):
    search_fields = ["title", "author", "pdf_file"]

admin.site.register(Booklet, BookletAdmin)

# Booklet page 
class BookletPage(models.Model):
    booklet = models.ForeignKey(Booklet, related_name='pages')
    page_number = models.IntegerField()

    def __unicode__(self):
        return str(self.page_number)


# An adapter class to enable an ordered list of songs within a booklet
class BookletSong(models.Model):
    booklet_page = models.ForeignKey(BookletPage, related_name='songs')
    song = models.ForeignKey(Song, related_name='booklet_songs')
    order_no = models.IntegerField()

    def __unicode__(self):
        return self.song.title


# Events such as sittnings, which booklets are associated with
class Event(models.Model):
    booklet = models.ForeignKey(Booklet, related_name='events')
    name = models.CharField(max_length=120)
    date = models.DateField()

    def __unicode__(self):
        return self.name


###### USER RELATED MODELS #######

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True, default=datetime.now())

    def __unicode__(self):
        str = ""
        str += u"username : " + self.user.username + u", "
        str += u"email : " + self.email + u", "
        str += u"first_name : " + self.first_name + u", "
        str += u"last_name : " + self.last_name
        return str

# Create a user profile automatically when a user is created
from django.db.models.signals import post_save


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance, email=instance.email)
post_save.connect(create_user_profile, sender=User)


class UserProfileForm(forms.ModelForm):

    error_messages = {
        'duplicate_username': "Käyttäjänimi on jo käytössä.",
        'email_in_use': "Sähköpostiosoite on jo käytössä.",
        'password_incorrect': "Virheellinen salasana.",
    }

    email = forms.EmailField(
        label="Sähköpostiosoite",
        widget=forms.EmailInput,
        required=True
    )

    password = forms.CharField(
        label="Salasana",
        widget=forms.PasswordInput,
        required=True,
    )

    class Meta:
        model = User

        fields = ['username', 'email', 'first_name', 'last_name', 'password']
        labels = {
            'username' : 'Käyttäjänimi',
            'email' : "Sähköposti",
            'first_name' : "Etunimi",
            'last_name' : "Sukunimi",
            'password' : 'Salasana',
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'edit-profile'
        self.helper.form_role = 'form'
        self.helper.form_action = 'edit_profile'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('save', 'Tallenna'))

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]

        if username != self.user.username:
            try:
                User._default_manager.get(username=username)
            except User.DoesNotExist:
                return username
            raise forms.ValidationError(
                self.error_messages['duplicate_username'],
                code='duplicate_username',
            )
        return username

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        if (not self.user.has_usable_password() or self.user.check_password(self.cleaned_data["password"])):
            return self.cleaned_data["password"]
        else:
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email != self.user.email:
            try:
                User._default_manager.get(email=email)
            except User.DoesNotExist:
                return email
            raise forms.ValidationError(
                self.error_messages['email_in_use'],
                code='email_in_use',
            )
        return email

    def save(self, commit=True):

        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        email = self.cleaned_data.get('email')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')

        self.user.username = username
        self.user.password = password
        self.user.email = email
        self.user.first_name = first_name
        self.user.last_name = last_name

        self.user.profile.email = email
        self.user.profile.first_name = first_name
        self.user.profile.last_name = last_name

        if commit:
            self.user.save()
            self.user.profile.save()


class UserProfileSocialForm(forms.ModelForm):

    error_messages = {
        'duplicate_username': "Käyttäjänimi on jo käytössä.",
        'email_in_use': "Sähköpostiosoite on jo käytössä.",
        'password_incorrect': "Virheellinen salasana.",
    }

    email = forms.EmailField(
        label="Sähköpostiosoite",
        widget=forms.EmailInput,
        required=True
    )

    class Meta:
        model = User

        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'username' : 'Käyttäjänimi',
            'email' : "Sähköposti",
            'first_name' : "Etunimi",
            'last_name' : "Sukunimi",
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UserProfileSocialForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'edit-profile'
        self.helper.form_role = 'form'
        self.helper.form_action = 'edit_profile'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('save', 'Tallenna'))

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]

        if username != self.user.username:
            try:
                User._default_manager.get(username=username)
            except User.DoesNotExist:

lasytunkki/Laulutunkki/templates/booklets/booklet.html
{% extends 'base.html' %}{% load i18n %}

{% block content %}
    <!-- Booklet information -->
    <div class="panel panel-default">
        <div class="panel-heading">
            {% if user.is_staff or user.id == booklet.author.id %}
                <a href="{% url 'delete_booklet' booklet.pk %}">
                    <span style="float: right; display: inline;" class="glyphicon glyphicon-trash"></span>
                </a>
            {% endif %}
            <h3 class="panel-title">{{ booklet.title }}</h3>
        </div>
        <div class="panel-body">
            <pre>
                <div class="front_page_text">Etusivu teksti: {{booklet.front_page_text }}</div>
                <div class="front_page_img">Kansikuvan URL: {{booklet.front_page_image}}</div>
                <div class="songs">{% for page in pages %}Sivu {{page|floatformat|add:"1"}}:{% for song in page.songs.all %}
    {{song.song}}{% endfor %}
<br>{% endfor %}
                </div>
            </pre>
            <a href="/get_booklet/{{ booklet.id }}">Lataa PDF</a>

            <div class="created"><strong>Luotu:</strong> {{ booklet.created|date:'Y-m-d H:i' }} / {{ booklet.author.username }}</div>
            {% with current=booklet %}                
            {% if current.previous_version %}
                </br>
                Vanhemmat (3) versiot tästä läsystä:
                <div> 
                {% with current=current.previous_version %}
                <a href="{% url 'booklet' current.pk %}"> {{ current.title}} ({{current.created|date}} by {{current.author.username}})</a></br>
                {% if current.previous_version %}
                    {% with current=current.previous_version %}
                    <a href="{% url 'booklet' current.pk %}"> {{ current.title}} ({{current.created|date}} by {{current.author.username}})</a></br>
                    {% if current.previous_version %}
                        {% with current=current.previous_version %}
                        <a href="{% url 'booklet' current.pk %}"> {{ current.title}} ({{current.created|date}} by {{current.author.username}})</a></br>
                        {% endwith %}
                    {% endif %}
                    {% endwith %}
                {% endif %}
                {% endwith %}
                </div>

            {% endif %}
            
            {% endwith %}
            {% if booklet.updated_version.all %}
                </br>
                Uudet versiot tästä läsystä:
                <div>
                    {% for newer in booklet.updated_version.all %}
                    <a href="{% url 'booklet' newer.pk %}"> {{ newer.title}} ({{newer.created|date}} by {{newer.author.username}})</a></br>
                    {% endfor %}
                </div>
                
            {% endif %}
            </br>
            {% if user.is_authenticated %}
                <a href="{% url 'edit_booklet' booklet.pk %}">   
                {% if user == booklet.author %}
                    <button type="button" class="btn btn-primary">Muokkaa läsyä</button>
                {% else %}
                    <button type="button" class="btn btn-primary">Kopioi läsy</button>
                {% endif %}
                </a>
            {%endif%}

            <br>
            <br>
            <!-- Facebook share link -->
            <!-- <a href="https://www.facebook.com/sharer/sharer.php?u=http://lasytunkki.herokuapp.com/booklet/{{ booklet.pk }}" target="_blank">
                Jaa läsy Facebookissa!
            </a> -->
            <div class="fb-share-button" data-href="http://lasytunkki.herokuapp.com/booklet/{{ booklet.pk }}" data-type="button_count"></div>

            <!-- Comments -->
            <h4>Kommentit</h4>
            {% load comments %}
            {% render_comment_list for booklet %}
            {% if user.is_authenticated %}
                {% render_comment_form for booklet %}
            {% else %}
                <p>
                    <a href="{% url "login" %}">Kirjaudu sisään</a> kirjoittaaksesi kommentteja.
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}

lasytunkki/Laulutunkki/templates/booklets/booklet_list.html
{% extends 'base.html' %}
{% block nav-booklet_list %}class="active"{% endblock %}

{% block content %}
    <!-- Create booklet -->
    {% if user.is_authenticated %}
        <p>
            <a href="{% url 'create_booklet' %}">
                <button type="button" class="btn btn-primary">Luo uusi läsy</button>
            </a>
        </p>
    {% endif %}

    <!-- Booklets -->
    {% if booklet_list.empty %}
    {% endif %}
    <div class="panel-group">
        {% for booklet in booklet_list.object_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% if user.is_staff or user.id == booklet.author.id %}
                        <a href="{% url 'delete_booklet' booklet.pk %}">
                            <span style="float: right; display: inline;" class="glyphicon glyphicon-trash"></span>
                        </a>
                    {% endif %}
                    <h3 class="panel-title">
                        <a href="{% url 'booklet' booklet.pk %}">
                            {{ booklet.title }}
                        </a>
                    </h3>
                    
                </div>
            </div>
        {% empty %}
            <p>
                Tietokannasta ei löytynyt yhtään läsyä.
            </p>
        {% endfor %}
    </div>

    <!-- Next/Prev page links  -->
    {% if booklet_list.object_list and booklet_list.paginator.num_pages > 1 %}
        <ul class="pagination">
            {% if booklet_list.has_previous %}
                <li><a href="?page={{ booklet_list.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><a href="#">&laquo;</a></li>
            {% endif %}

            {% for i in booklet_list.paginator.page_range %}
                {% if i == booklet_list.number  %}
                    <li class="active"><a href="#">{{ i }}<span class="sr-only">(current)</span></a></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if booklet_list.has_next %}
                <li><a href="?page={{ booklet_list.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><a href="#">&raquo;</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

lasytunkki/Laulutunkki/templates/booklets/create_booklet.html
{% extends 'base.html' %}
{% block nav-booklet_list %}class="active"{% endblock %}
{% block script %}
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/create_booklet.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/select2_locale_fi.js"></script>

{% endblock %}

{% block content %}
{% csrf_token %}
    <h3>Luo uusi läsy</h3>
    <div class="main container">
        <div class="row">

            <!-- TITLE FIELD -->
            <div id="div_id_title" class="form-group">
                <label for="id_title" class="control-label  requiredField">
                Läsyn nimi<span class="asteriskField">*</span>
                </label>
                <div class="controls ">
                    <input class="textinput textInput form-control" id="id_title" maxlength="120" name="title" type="text">
                </div>
            </div>

            <!-- FRONT PAGE TEXT -->
            <div id="div_id_front_page_text" class="form-group">
                <label for="id_front_page_text" class="control-label  requiredField">
                Läsyn etusivun teksti (hyväksyy Tex-formaattia)<span class="asteriskField"></span>
                </label>
                <div class="controls ">
                    <input class="textinput textInput form-control" id="id_front_page_text" maxlength="120" name="front_page_text" type="text">
                </div>
            </div>

            <!-- FRONT PAGE IMAGE URL -->
            <div id="div_id_front_page_image_url" class="form-group">
                <label for="id_front_page_image_url" class="control-label  requiredField">
                Linkki läsyn etusivu kuvaan (oltava muodossa .jpg, suurin sallittu koko 10mb)<span class="asteriskField"></span>
                </label>
                <div class="controls ">
                    <input class="textinput textInput form-control" id="id_front_page_image_url" maxlength="120" name="front_page_image_url" type="text">
                </div>
            </div>

            <!-- FLICKR SEARCH TOGGLE -->
            <div class="form-group">
              <a href="#" id="flickr_toggle">Hae läsyn etusivun kuva Flickrista</a>
            </div>
            
            <!-- FLICKR IMAGE SEARCH -->
            <div id="id_flickr" class="well" style="display:none;">
              <div id="div_id_flickr" class="form-group">
                  <label for="flickr_search">Kirjoita hakusana
                  </label>
                  <div class="controls">
                    <input class="textinput textInput form-control" type="text" id="flickr_search">
                    <br>
                    <input class="btn btn-primary" type="submit" value="Hae" onclick="searchFunction()">
                  </div>
              </div>
              <div id="images">
                <div id="thumbnailCarousel" class="carousel slide">
                  <div id="thumbnailContainer" class="carousel-inner"></div>
                  <a style="display: none;" id="leftCarouselControl" class="left carousel-control" href="#thumbnailCarousel" data-slide="prev">&lt;</a>
                  <a style="display: none;" id="rightCarouselControl" class="right carousel-control" href="#thumbnailCarousel" data-slide="next">&gt;</a>
                </div>
              </div>
            </div>
            <!-- SONG LIST -->
            <div id="div_id_search" class="form-group">
                <label for="id_search" class="control-label  requiredField">
                Läsyn tulevat laulut<span class="asteriskField">*</span>
                </label>
                <div class="controls ">
                    <input multiple class="textinput textInput form-control select2-input select2-default" type="hidden" id="id_search" style="">
                </div>
            </div>

        </div>
        <input type="submit" value="Lähetä" class="btn btn-primary" id="choose">

    </div>
{% endblock %}

lasytunkki/Laulutunkki/templates/booklets/edit_booklet.html
{% extends 'base.html' %}
{% block nav-booklet_list %}class="active"{% endblock %}
{% block script %}
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/create_booklet.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/select2_locale_fi.js"></script>

{% endblock %}

{% block content %}
{% csrf_token %}
    <h3>Muokkaa läsyä</h3>
    <div class="main container">
        <div class="row">
            <div type="hidden" value="{{booklet.id}}" id="booklet_id"></div>
            <!-- TITLE FIELD -->
            <div id="div_id_title" class="form-group">
                <label for="id_title" class="control-label  requiredField">
                Läsyn nimi<span class="asteriskField">*</span>
                </label>
                <div class="controls ">
                    <input class="textinput textInput form-control" id="id_title" maxlength="120" name="title" type="text" value="{{booklet.title}}">
                </div>
            </div>

            <!-- FRONT PAGE TEXT -->
            <div id="div_id_front_page_text" class="form-group">
                <label for="id_front_page_text" class="control-label  requiredField">
                Läsyn etusivun teksti (hyväksyy Tex-formaattia)<span class="asteriskField"></span>
                </label>
                <div class="controls ">
                    <input class="textinput textInput form-control" id="id_front_page_text" maxlength="120" name="front_page_text" type="text" value="{{booklet.front_page_text}}">
                </div>
            </div>

            <!-- FRONT PAGE IMAGE URL -->
            <div id="div_id_front_page_image_url" class="form-group">
                <label for="id_front_page_image_url" class="control-label  requiredField">
                Linkki läsyn etusivu kuvaan (oltava muodossa .jpg, suurin sallittu koko 10mb)<span class="asteriskField"></span>
                </label>
                <div class="controls ">
                    <input class="textinput textInput form-control" id="id_front_page_image_url" maxlength="120" name="front_page_image_url" type="text" value="{{booklet.front_page_image}}">
                </div>
            </div>
            
            <!-- FLICKR SEARCH TOGGLE -->
            <div class="form-group">
              <a href="#" id="flickr_toggle">Hae läsyn etusivun kuva Flickrista</a>
            </div>
            
            <!-- FLICKR IMAGE SEARCH -->
            <div id="id_flickr" class="well" style="display:none;">
              <div id="div_id_flickr" class="form-group">
                  <label for="flickr_search">Kirjoita hakusana
                  </label>
                  <div class="controls">
                    <input class="textinput textInput form-control" type="text" id="flickr_search">
                    <br>
                    <input class="btn btn-primary" type="submit" value="Hae" onclick="searchFunction()">
                  </div>
              </div>
              <div id="images">
                <div id="thumbnailCarousel" class="carousel slide">
                  <div id="thumbnailContainer" class="carousel-inner"></div>
                  <a style="display: none;" id="leftCarouselControl" class="left carousel-control" href="#thumbnailCarousel" data-slide="prev">&lt;</a>
                  <a style="display: none;" id="rightCarouselControl" class="right carousel-control" href="#thumbnailCarousel" data-slide="next">&gt;</a>
                </div>
              </div>
            </div>

            <!-- SONG LIST -->
            <div id="div_id_search" class="form-group">
                <label for="id_search" class="control-label  requiredField">
                Läsyn tulevat laulut<span class="asteriskField">*</span>
                </label>
                <div class="controls ">
                    <input multiple class="textinput textInput form-control select2-input select2-default" type="hidden" id="id_search" style="">
                </div>
            </div>

        </div>
        <input type="submit" value="Tallenna" class="btn btn-primary" id="choose">

    </div>

    <script type="text/javascript">
        $( document ).ready(function() {
            var a = [{% for song in songs %}
                {id: {{song.pk}}, text: '{{song}}'},
                {% endfor %}];
            $("#id_search").select2("data", a);
        })
    </script>
    
{% endblock %}